
version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://db:27017/yolo_db
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: