
version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "3001:80"
  
  backend:
    build: ./backend
    container_name: yolo-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://db:27017/yolo_db
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: yolo-db
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: