---
- name: Pull image from repository
  docker_image:
    name: njengamoses/yolo-backend:v1.0.0
    source: pull

- name: Create Node.js yolo-backend Container
  docker_container:
    name: yolo-backend
    image: njengamoses/yolo-backend:v1.0.0
    networks:
      - name: app-net
    ports:
      - "5000:5000"
    state: started
    restart_policy: always
  become: yes